### ISSUE TITLE
Required test data

### ISSUE THREAD

**Issue by lacardonap** [Hollweg/IONEX#1]
@Hollweg Thank you very much for your contribution, I would like to know if I can have access to a set of test data with which I can test the scripts. I'm new at this.

Thank you very much.

**Comment by Hollweg** [comment]
Hello, @lacardonap... Sorry for the late delay.
Please, send me an email I can send you the test data (if you still needs it hehe).
Best regards!

**Comment by lacardonap** [comment]
@Hollweg  thank you very much for your answer, your repository was very useful to be able to convert a custom dataset to IONEX format. At this moment I don't need the file but in case I need it I will not hesitate to write you. Thank you very much. 

Cheers Leo
